FROM python:3.9-slim

WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000


ENV FLASK_APP=app.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0"]

